<?php
/*
 * Pepipost\PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace Pepipost\PepipostLib\Http\Controllers;

use Pepipost\PepipostLib\HttpRequest\HttpCallBack;
use Pepipost\PepipostLib\HttpRequest\HttpContext;
use Pepipost\PepipostLib\HttpRequest\HttpResponse;
use Pepipost\PepipostLib\APIException;
use Pepipost\PepipostLib\Exceptions;
use \apimatic\jsonmapper\JsonMapper;
use App\Http\Controllers\Controller;
use Unirest\Request;

/**
* Base controller
*/
class BaseController extends Controller
{
    /**
     * User-agent to be sent with API calls
     * @var string
     */
    const USER_AGENT = 'pepi-sdk-php-v5.1';

    /**
     * HttpCallBack instance associated with this controller
     * @var HttpCallBack
     */
    private $httpCallBack = null;

    /**
     * Set HttpCallBack for this controller
     * @param HttpCallBack $httpCallBack Http Callbacks called before/after each API call
     */
    public function setHttpCallBack(HttpCallBack $httpCallBack)
    {
        $this->httpCallBack = $httpCallBack;
    }

    /**
     * Get HttpCallBack for this controller
     * @return HttpCallBack The HttpCallBack object set for this controller
     */
    public function getHttpCallBack()
    {
        return $this->httpCallBack;
    }

    /**
     * Get a new JsonMapper instance for mapping objects
     * @return \apimatic\jsonmapper\JsonMapper JsonMapper instance
     */
    protected function getJsonMapper()
    {
        $mapper = new JsonMapper();
        return $mapper;
    }

    protected function validateResponse(HttpResponse $response, HttpContext $_httpContext)
    {
        if (($response->getStatusCode() < 200) || ($response->getStatusCode() > 208)) { //[200,208] = HTTP OK
            throw new APIException('HTTP Response Not OK', $_httpContext);
        }
    }
}
