<?php
/*
 * Pepipost\PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace Pepipost\PepipostLib\Models;

use JsonSerializable;

/**
 *Attachments
 */
class Attachments implements JsonSerializable
{
    /**
     * Base64 encoded value of the attached file
     * @var string|null $content public property
     */
    public $content;

    /**
     * filename of attachments
     * @var string|null $name public property
     */
    public $name;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $content Initialization value for $this->content
     * @param string $name    Initialization value for $this->name
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->content = func_get_arg(0);
            $this->name    = func_get_arg(1);
        }
    }
    
    /**
     * file content extractor
     * @param string $file_path Path of the file to be sent to the email
     */
    public function attach($file_path)
    {
        $this->name = basename($file_path);
        $this->content = base64_encode(file_get_contents($file_path));
    }

    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['content'] = $this->content;
        $json['name']    = $this->name;

        return $json;
    }
}
